spring:
  datasource:
    url: jdbc:sqlserver://factory-server.database.windows.net:1433;database=factory-db;encrypt=true;trustServerCertificate=false;hostNameInCertificate=*.database.windows.net;loginTimeout=30;
    username: dbadmin
    password: db@admin12345
  jpa:
    show-sql: true
    hibernate: 
      ddl-auto: update
      dialect : org.hibernate.dialect.SQLServer2012Dialect
    
server:
  port: 9998
  
  
  